apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: harisathwik/streamlit_app:${{ github.sha }}
          ports:
            - containerPort: 8501
          env:
            - name: PUBLIC_URL
              value: "http://localhost:8501" # Change the port to match your Streamlit app port
