apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
spec:
  replicas: 3  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app-container
        image: harisathwik/streamlit_app:v1  # Replace with your actual container image URL
        ports:
        - containerPort: 8501
